### PR TITLE
[FE] show error messages on FE

### PR DESCRIPTION
**Pull request by sajjadmurtaza**

### CODE REVIEW

**Comment by WebFa98** [comment]
Screenshot 2023-12-10 165634
it seems like there is an issue with the logic right now it gives me the error message but still tries to send the empty message

**Comment by garvinkon** [comment]
We should wait with merging that, until the ticket 91 is merged. Because we have a little error handling in it  aswell. We will add the PR in the evening, when i added the tests. We should speak about it again. @sajjadmurtaza @Gnagniko @WebFa98

**Comment by sajjadmurtaza** [comment]
> Screenshot 2023-12-10 165634
> 
> it seems like there is an issue with the logic right now it gives me the error message but still tries to send the empty message

I'll fix that and wait for other PR to merge as well

**Review by WebFa98 — APPROVED** [review]
Looks good. Talked with Garvin about it. There shouldnt be any merge conflicts with ticket 91.

**Pull request merged**
