### PR TITLE
Connected model to endpoint. Updated test and readme.

### PR DESCRIPTION
**Pull request by irhox**

### CODE REVIEW

**Review by Gnagniko — APPROVED** [review]
Works fine

**Comment by sajjadmurtaza** [comment]
@irhox @Gnagniko did you run the tests or use /text endpoint after making changes? it's taking too much time to load, Please do either refactoring or putting in cron/backend job run model thingi.

**Comment by irhox** [comment]
@sajjadmurtaza it talks some time to load the first time because it is downloading the model. After that it is still slow but not that bad. The model just needs its time to process the text. Did you try it out a couple of times?

**Comment by sajjadmurtaza** [comment]
@irhox best way to handle this kind of stuff by using cron jobs. for now might be ok
https://www.loom.com/share/944b48b6495241aaac47c2fd1810c2cf

https://www.youtube.com/watch?v=m5H54NcvBRU&ab_channel=KavyanshPandey

**Pull request merged**
