### PR TITLE
Feature 34 add database to backend

### PR DESCRIPTION
**Pull request by M-HRL**
…ry and refactored backend structure

### CODE REVIEW

**Comment by M-HRL** [comment]
@Gnagniko, I assume that you're using Windows, right? If yes, please try to execute the test after installing the mongodb community server as referenced in the README and the python requirements.

**Comment by M-HRL** [comment]
@WebFa98, please rerun the test on your Linux machine, thanks!

**Comment by sajjadmurtaza** [comment]
I believe keeping the folders named 'Models' and 'Tests' is appropriate, as they accurately reflect the presence of multiple files. WDYT?

**Comment by M-HRL** [comment]
> I believe keeping the folders named 'Models' and 'Tests' is appropriate, as they accurately reflect the presence of multiple files. WDYT?

@sajjadmurtaza, it‘s a common practice to call folders more like a domain, not indicate how much is in there.

**Review by WebFa98 — APPROVED** [review]
Tests are working on Linux, Code looks good.

**Comment by sajjadmurtaza** [comment]
> > I believe keeping the folders named 'Models' and 'Tests' is appropriate, as they accurately reflect the presence of multiple files. WDYT?
> 
> @sajjadmurtaza, it‘s a common practice to call folders more like a domain, not indicate how much is in there.
> 
> image

it's fine as i said but stackoverflow said different answer
https://stackoverflow.com/questions/64943693/what-are-the-best-practices-for-structuring-a-fastapi-project#answer-64987404
Screenshot 2023-11-12 at 14 58 24




even on github
https://github.com/ycd/manage-fastapi

**Review by Gnagniko — APPROVED** [review]
Test works on windows

**Pull request merged**
